//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twitch_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.UserGame = new HashSet<UserGame>();
        }
    
        public int gameId { get; set; }
        public string title { get; set; }
        public System.DateTime releaseDate { get; set; }
        public string publishers { get; set; }
        public string bio { get; set; }
        public string developer { get; set; }
        public string mode { get; set; }
        public string platform { get; set; }
        public Nullable<int> gamecategoryId { get; set; }
    
        public virtual Gamecategory Gamecategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserGame> UserGame { get; set; }
    }
}
