//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twitch_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TwitchEntities : DbContext
    {
        public TwitchEntities()
            : base("name=TwitchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<Gamecategory> Gamecategory { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethod { get; set; }
        public virtual DbSet<Prime> Prime { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserGame> UserGame { get; set; }
        public virtual DbSet<UserPrime> UserPrime { get; set; }
        public virtual DbSet<Wallet> Wallet { get; set; }
    }
}
