//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twitch_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UsersGames = new HashSet<UserGame>();
            this.UsersPrimes = new HashSet<UserPrime>();
        }
    
        public int userId { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string mail { get; set; }
        public string displayname { get; set; }
        public string bio { get; set; }
        public string title { get; set; }
        public string language { get; set; }
        public Nullable<int> walletId { get; set; }
    
        public virtual Wallet Wallets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserGame> UsersGames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPrime> UsersPrimes { get; set; }
    }
}
